<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Seeder;

final class RegionSeeder extends Seeder
{
    /**
     * @return void
     */
    public function run(): void
    {
        $regions = array(

            "Amudaryo tumani",
            "Beruniy tumani",
            "Kegayli tumani",
            "Qonliko‘l tumani",
            "Qorao‘zak tumani",
            "Qo‘ng‘irot tumani",
            "Mo‘ynoq tumani",
            "Nukus tumani",
            "Nukus shahri",
            "Taxtako‘pir tumani",
            "To‘rtko‘l tumani",
            "Xo‘jayli tumani",
            "Chimboy tumani",
            "Shumanay tumani",
            "Ellikqal‘a tumani",
            "Andijon shahri",
            "Andijon tumani",
            "Asaka tumani",
            "Baliqchi tumani",
            "Buloqboshi tumani",
            "Bo‘z tumani",
            "Jalaquduq tumani",
            "Izbosgan tumani",
            "Qorasuv shahri",
            "Qo‘rg‘ontepa tumani",
            "Marhamat tumani",
            "Oltinko‘l tumani",
            "Paxtaobod tumani",
            "Ulug‘nor tumani",
            "Xonabod tumani",
            "Xo‘jaobod tumani",
            "Shaxrixon tumani",
            "Buxoro shahri",
            "Buxoro tumani",
            "Vobkent tumani",
            "G‘ijduvon tumani",
            "Jondor tumani",
            "Kogon tumani",
            "Kogon shahri",
            "Qorako‘l tumani",
            "Qorovulbozor tumani",
            "Olot tumani",
            "Peshku tumani",
            "Romitan tumani",
            "Shofirkon tumani",
            "Arnasoy tumani",
            "Baxmal tumani",
            "G‘allaorol tumani",
            "Do‘stlik tumani",
            "ShRashidov tumani",
            "Jizzax shahri",
            "Zarbdor tumani",
            "Zafarobod tumani",
            "Zomin tumani",
            "Mirzacho‘l tumani",
            "Paxtakor tumani",
            "Forish tumani",
            "Yangiobod tumani",
            "G‘uzor tumani",
            "Dehqonobod tumani",
            "Qamashi tumani",
            "Qarshi tumani",
            "Qarshi shahri",
            "Kasbi tumani",
            "Kitob tumani",
            "Koson tumani",
            "Mirishkor tumani",
            "Muborak tumani",
            "Nishon tumani",
            "Chiroqchi tumani",
            " shahrisabz tumani",
            "Yakkabog‘ tumani",
            "Zarafshon shahri",
            "Karman tumani",
            "Qiziltepa tumani",
            "Konimex tumani",
            "Navbahor tumani",
            "Navoiy shahri",
            "Nurota tumani",
            "Tomdi tumani",
            "Uchquduq tumani",
            "Xatirchi tumani",
            "Kosonsoy tumani",
            "Mingbuloq tumani",
            "Namangan tumani",
            "Namangan shahri",
            "Norin tumani",
            "Pop tumani",
            "To‘raqo‘rg‘on tumani",
            "Uychi tumani",
            "Uchqo‘rg‘on tumani",
            "Chortoq tumani",
            "Chust tumani",
            "Yangiqo‘rg‘on tumani",
            "Bulung‘ur tumani",
            "Jomboy tumani",
            "Ishtixon tumani",
            "Kattaqo‘rg‘on tumani",
            "Kattaqo‘rg‘on shahri",
            "Qo‘shrabot tumani",
            "Narpay tumani",
            "Nurabod tumani",
            "Oqdaryo tumani",
            "Payariq tumani",
            "Pastarg‘om tumani",
            "Paxtachi tumani",
            "Samarqand tumani",
            "Samarqand shahri",
            "Toyloq tumani",
            "Urgut tumani",
            "Angor tumani",
            "Boysun tumani",
            "Denov tumani",
            "Jarqo‘rg‘on tumani",
            "Qiziriq tumani",
            "Qo‘mqo‘rg‘on tumani",
            "Muzrabot tumani",
            "Oltinsoy tumani",
            "Sariosiy tumani",
            "Termiz tumani",
            "Termiz shahri",
            "Uzun tumani",
            "Sherobod tumani",
            "Sho‘rchi tumani",
            "Boyovut tumani",
            "Guliston tumani",
            "Guliston shahri",
            "Mirzaobod tumani",
            "Oqoltin tumani",
            "Sayxunobod tumani",
            "Sardoba tumani",
            "Sirdaryo tumani",
            "Xavos tumani",
            "Shirin shahri",
            "Yangiyer shahri",
            "Angiren shahri",
            "Bekabod tumani",
            "Bekabod shahri",
            "Bo‘ka tumani",
            "Bo‘stonliq tumani",
            "Zangiota tumani",
            "Qibray tumani",
            "Quyichirchiq tumani",
            "Oqqo‘rg‘on tumani",
            "Olmaliq shahri",
            "Ohangaron tumani",
            "Parkent tumani",
            "Piskent tumani",
            "O‘rtachirchiq tumani",
            "Chinoz tumani",
            "Chirchiq shahri",
            "Yuqorichirchiq tumani",
            "Yangiyo‘l tumani",
            "Beshariq tumani",
            "Bog‘dod tumani",
            "Buvayda tumani",
            "Dang‘ara tumani",
            "Yozyovon tumani",
            "Quva tumani",
            "Quvasoy shahri",
            "Qo‘qon shahri",
            "Qo‘shtepa tumani",
            "Marg‘ilon shahri",
            "Oltiariq tumani",
            "Rishton tumani",
            "So‘x tumani",
            "Toshloq tumani",
            "Uchko‘prik tumani",
            "O‘zbekiston tumani",
            "Farg‘ona tumani",
            "Farg‘ona shahri",
            "Furqat tumani",
            "Bog‘ot tumani",
            "Gurlan tumani",
            "Qo‘shko‘pir tumani",
            "Urganch tumani",
            "Urganch shahri",
            "Xiva tumani",
            "Xazarasp tumani",
            "Xonqa tumani",
            "Shavot tumani",
            "Yangiariq tumani",
            "Yangibozor tumani",
            "Bektimer tumani",
            "MirzoUlug‘bek tumani",
            "Mirobod tumani",
            "Olmazor tumani",
            "Sirg‘ali tumani",
            "Uchtepa tumani",
            "Yashnobod tumani",
            "Chilonzor tumani",
            "Shayxontohur tumani",
            "Yunusobod tumani",
            "Yakkasaroy tumani",
            "Taxiatosh shahri",
            "Asaka shahri",
            "Bandixon tumani",
            "Ohangaron shahri",
            "Yangiyo‘l shahri",
            "Toshkent tumani",
            "Xiva shahri",
            "Do‘stlik shahri",
            "Yangihayot tumani",
            "Tuproqqala tumani",

        );



        Region::insert($regions);
    }
}
