#!/usr/bin/env php
<?php

ini_set('memory_limit', '-1');

use Illuminate\Contracts\Console\Kernel;

use Symfony\Component\Console\Input\ArgvInput;

use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

define('STDIN',fopen("php://stdin","r"));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
*/

require __DIR__ . '/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
*/

$app = require_once __DIR__ . '/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
*/

$kernel = $app->make(Kernel::class);

$status = $kernel->handle($input = new ArgvInput, new ConsoleOutput);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
*/

$kernel->terminate($input, $status);

exit($status);
