apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: silkroad
    type: sr-api-deployment
  name: sr-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silkroad
      type: sr-api-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: silkroad
        type: sr-api-pod
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: sr-api-configmap
        image: 307856681743.dkr.ecr.us-east-2.amazonaws.com/dev-sr-api:latest
        imagePullPolicy: Always
        name: sr-api-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
